[auth]
# Specify the primary provider for username/password login
primary_provider = "mock"

# Configuration for the primary provider
[auth.providers.mock]
username = "testuser"
password_hash = "$argon2id$v=19$m=19456,t=2,p=1$0PrJ56wh4Ls9lL2Ivo3S/A$6juEaOEMVMgIOfaJWxpafkuJ9Sx5zO4sEl28TwlU2ek"

# Configuration for secondary SSO providers
[auth.sso_providers.google]
client_id = "382158762481-lmlov3r9dlnujgq8e1ks6otp6tmne1bp.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "http://localhost:8080/api/auth/sso/callback/google"

[auth.sso_providers.microsoft]
client_id = "196d7484-2cd0-4341-9231-0686279aaff9"
client_secret = "kTW8Q~60zwWzMdHoU9Pr7cZdfC0kqH21ON_Lhc0x"
redirect_uri = "http://localhost:8080/api/auth/sso/callback/microsoft"

[auth.sso_providers.apple]
client_id = "YOUR_APPLE_CLIENT_ID"
client_secret = "YOUR_APPLE_CLIENT_SECRET"
redirect_uri = "http://localhost:8080/api/auth/sso/callback/apple"
